import PDFDocument from 'pdfkit';
import QRCode from 'qrcode';
import fs from 'fs';
import path from 'path';
import Quote, { IQuote } from '../models/Quote';
import { capitalizeFirstWord } from './capitalizeFirstWord';

export const generateQuotePdfBuffer = async (id: string): Promise<Buffer | null> => {
  try {
    const quote = (await Quote.findById(id)) as IQuote;
    if (!quote) return null;

    // Generate QR
    const qrDataUrl = await QRCode.toDataURL(
      'https://calendar.google.com/calendar/appointments/schedules/AcZssZ2W1GSYMgYtE6TgiADihyLe7-kcY-T6MmmLlwSd8W169fBgCb_iMizBTyadSP3CB-SvumvNczuz?gv=true',
      {
        width: 150,
        margin: 1,
        color: { dark: '#0057D9', light: '#FFFFFF' },
      }
    );
    const qrBuffer = Buffer.from(qrDataUrl.split(',')[1], 'base64');

    // Collect PDF chunks in memory
    const chunks: Buffer[] = [];

    const doc = new PDFDocument({
      margin: 50,
      size: 'A4',
      info: {
        Title: `Trakshym Quote ${quote.publicId}`,
        Author: 'Trakshym Solutions',
        Subject: 'Project Estimation',
        Creator: 'Trakshym Estimator',
      },
    });

    // Register unicode font
    doc.registerFont('NotoSans', path.join(__dirname, '../assets/fonts/NotoSans-Regular.ttf'));

    // Collect data
    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => {});

    // ============ ENHANCED COLOR PALETTE ============
    // More professional: Deeper blues, grays, and accents for a modern, trustworthy look
    const colors = {
      primary: '#1E3A8A', // Deeper navy blue
      secondary: '#3B82F6', // Vibrant blue
      darkText: '#0F172A', // Dark gray
      mediumText: '#475569', // Medium gray
      lightText: '#6B7280', // Light gray
      sectionBg: '#F9FAFB', // Softer off-white
      borderColor: '#D1D5DB', // Lighter border
      accentGreen: '#059669', // Deeper green
      accentBlue: '#0EA5E9', // Sky blue
      accentPurple: '#7C3AED', // Deeper purple
      warningAmber: '#D97706', // Softer amber
      successGreen: '#10B981',
      white: '#FFFFFF',
    };
    // const colors = {
    //   primary: '#0F172A',
    //   secondary: '#1E40AF',
    //   darkText: '#0F172A',
    //   mediumText: '#475569',
    //   lightText: '#64748B',
    //   sectionBg: '#F8FAFC',
    //   borderColor: '#E2E8F0',
    //   accentGreen: '#10B981',
    //   accentBlue: '#3B82F6',
    //   accentPurple: '#8B5CF6',
    //   warningAmber: '#F59E0B',
    //   successGreen: '#059669',
    //   white: '#FFFFFF',
    // };

    const pageWidth = 595.28; // A4 width
    const pageHeight = 841.89; // A4 height
    const margin = 50;
    const contentWidth = pageWidth - margin * 2;

    // ============ HELPER FUNCTIONS ============

    const addFooter = (pageNum: number, totalPages: number) => {
      doc
        .fontSize(10)
        .fillColor(colors.lightText)
        .font('Helvetica')
        .text('Auto-generated by Trakshym Estimator v1.0', margin, pageHeight - 74, {
          width: contentWidth / 3,
        })
        .fontSize(10)
        .fillColor(colors.lightText)
        .text(quote.publicId, margin + contentWidth / 3, pageHeight - 74, {
          width: contentWidth / 3,
          align: 'center',
        })
        .fontSize(10)
        .fillColor(colors.lightText)
        .text(
          `Page ${pageNum} of ${totalPages}`,
          margin + (contentWidth * 2) / 3,
          pageHeight - 74,
          { width: contentWidth / 3, align: 'right' }
        );
    };

    const drawDivider = (y: number, color = colors.borderColor, thickness = 1) => {
      // Thicker divider
      doc
        .strokeColor(color)
        .lineWidth(thickness)
        .moveTo(margin, y)
        .lineTo(pageWidth - margin, y)
        .stroke();
    };

    const drawSectionBox = (
      x: number,
      y: number,
      width: number,
      height: number,
      bgColor: string,
      borderCol = colors.primary,
      radius = 12
    ) => {
      if ((doc as any)._pdfkitRoundedRect) {
        // Ensure roundedRect is available; PDFKit supports it natively
        doc.roundedRect(x, y, width, height, radius).fillAndStroke(bgColor, borderCol);
      } else {
        // Fallback to rect if roundedRect not supported in version
        doc.rect(x, y, width, height).fillAndStroke(bgColor, borderCol);
      }
    };

    const getValidityDate = () => {
      const date = new Date();
      date.setDate(date.getDate() + 30);
      return date;
    };

    // Helper to add rounded image (for logo)
    const addRoundedImage = (
      imageBuffer: Buffer,
      x: number,
      y: number,
      width: number,
      height: number,
      radius: number = 8
    ) => {
      doc.save();
      doc.roundedRect(x, y, width, height, radius).clip(); // Clip to rounded rect
      doc.image(imageBuffer, x, y, { width, height }); // Draw image
      doc.restore();
    };

    // Helper to draw text with ₹ symbol (switch to a font that supports Unicode if embedded)
    const drawRupeesText = (
      text: string,
      x: number,
      y: number,
      options: { fontSize?: number; fillColor?: string }
    ) => {
      doc
        .font('NotoSans')
        .fontSize(options.fontSize || 12)
        .fillColor(options.fillColor || colors.darkText)
        .text(text, x, y);
    };

    // ============ PAGE 1: COVER & EXECUTIVE SUMMARY ============

    // Header background - Softer gradient-like with secondary accent
    doc.rect(0, 0, pageWidth, 200).fill(colors.darkText); // Slightly taller header

    // --- Logo ---
    let logoWidth = 60;
    let logoHeight = 60;
    let logoX = margin;
    let logoY = 40; // balanced from top

    try {
      const logoPath = path.join(process.cwd(), 'src/assets/logo.png');
      const logoBuffer = await fs.promises.readFile(logoPath);

      addRoundedImage(logoBuffer, logoX, logoY, logoWidth, logoHeight, 10);
    } catch (err) {
      console.error('Logo not found:', err);
    }

    // --- Text ---
    const textX = logoX + logoWidth + 20; // 20px space after logo
    const textY = logoY + logoHeight / 2 - 12;
    // 32 font / 2 = 16 → vertically center the text

    doc.fontSize(32).fillColor(colors.white).font('Helvetica-Bold').text('TRAKSHYM', textX, textY);

    // Title - Larger and more spaced
    doc
      .fontSize(24)
      .fillColor(colors.white)
      .font('Helvetica-Bold')
      .text('PROJECT ESTIMATION', margin, 110, { width: contentWidth })
      // .fontSize(24)
      .text('REPORT', margin, 155, { width: contentWidth });

    let currentY = 230; // Adjusted for taller header

    // Metadata cards - Larger and better spaced, increased height for Quote Number
    const metaBoxWidth = (contentWidth - 20) / 3; // More space between
    const metaBoxHeight = 76;
    const validityDate = getValidityDate();

    // Box 1: Quote Number - Adjusted positions for single line
    drawSectionBox(margin, currentY, metaBoxWidth, metaBoxHeight, colors.white, colors.primary);
    doc
      .fontSize(11)
      .fillColor(colors.mediumText)
      .font('Helvetica')
      .text('Quote Number', margin + 15, currentY + 20, { width: metaBoxWidth - 30 }) // More top padding
      .fontSize(14)
      .fillColor(colors.primary)
      .font('Helvetica-Bold')
      .text(quote.publicId, margin + 15, currentY + 45, { width: metaBoxWidth - 30 }); // Lower position

    // Box 2: Generated Date
    const box2X = margin + metaBoxWidth + 10;
    drawSectionBox(box2X, currentY, metaBoxWidth, metaBoxHeight, colors.white, colors.accentBlue);
    doc
      .fontSize(11)
      .fillColor(colors.mediumText)
      .font('Helvetica')
      .text('Generated', box2X + 15, currentY + 20, { width: metaBoxWidth - 30 })
      .fontSize(14)
      .fillColor(colors.accentBlue)
      .font('Helvetica-Bold')
      .text(
        new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' }),
        box2X + 15,
        currentY + 45,
        { width: metaBoxWidth - 30 }
      );

    // Box 3: Valid Until
    const box3X = margin + metaBoxWidth * 2 + 20;
    drawSectionBox(box3X, currentY, metaBoxWidth, metaBoxHeight, colors.white, colors.warningAmber);
    doc
      .fontSize(11)
      .fillColor(colors.mediumText)
      .font('Helvetica')
      .text('Valid Until', box3X + 15, currentY + 20, { width: metaBoxWidth - 30 })
      .fontSize(14)
      .fillColor(colors.warningAmber)
      .font('Helvetica-Bold')
      .text(
        validityDate.toLocaleDateString('en-US', {
          year: 'numeric',
          month: 'short',
          day: 'numeric',
        }),
        box3X + 15,
        currentY + 45,
        { width: metaBoxWidth - 30 }
      );

    currentY += 110; // More space

    // Client Details - Two columns, larger fonts
    doc
      .fontSize(16)
      .font('Helvetica-Bold')
      .fillColor(colors.darkText)
      .text('CLIENT DETAILS', margin, currentY);

    currentY += 25; // More space
    drawDivider(currentY);
    currentY += 15;

    // Left column
    doc.fontSize(11).fillColor(colors.mediumText).font('Helvetica').text('Name:', margin, currentY);
    doc
      .fontSize(12)
      .fillColor(colors.darkText)
      .font('Helvetica-Bold')
      .text(quote.client.name, margin + 60, currentY); // More indent

    currentY += 20;
    doc
      .fontSize(11)
      .fillColor(colors.mediumText)
      .font('Helvetica')
      .text('Email:', margin, currentY);
    doc
      .fontSize(12)
      .fillColor(colors.darkText)
      .font('Helvetica-Bold')
      .text(quote.client.email, margin + 60, currentY);

    currentY += 20;
    doc
      .fontSize(11)
      .fillColor(colors.mediumText)
      .font('Helvetica')
      .text('Phone:', margin, currentY);
    doc
      .fontSize(12)
      .fillColor(colors.darkText)
      .font('Helvetica-Bold')
      .text(quote.client.phone, margin + 60, currentY);

    currentY += 20;
    if (quote.client.company) {
      doc
        .fontSize(11)
        .fillColor(colors.mediumText)
        .font('Helvetica')
        .text('Company:', margin, currentY);
      doc
        .fontSize(12)
        .fillColor(colors.darkText)
        .font('Helvetica-Bold')
        .text(quote.client.company, margin + 60, currentY);
      currentY += 20;
    }

    // Right column
    const rightColX = margin + contentWidth / 2;
    currentY -= quote.client.company ? 80 : 60; // Adjusted

    doc
      .fontSize(11)
      .fillColor(colors.mediumText)
      .font('Helvetica')
      .text('Engagement Model:', rightColX, currentY);
    doc
      .fontSize(12)
      .fillColor(colors.primary)
      .font('Helvetica-Bold')
      .text(quote.engagementModel.toUpperCase(), rightColX + 140, currentY); // More space

    currentY += 20;
    doc
      .fontSize(11)
      .fillColor(colors.mediumText)
      .font('Helvetica')
      .text('User Profile:', rightColX, currentY);
    doc
      .fontSize(12)
      .fillColor(colors.primary)
      .font('Helvetica-Bold')
      .text(quote.userProfile.toUpperCase(), rightColX + 140, currentY);

    currentY += 20;
    doc
      .fontSize(11)
      .fillColor(colors.mediumText)
      .font('Helvetica')
      .text('Status:', rightColX, currentY);
    doc
      .fontSize(12)
      .fillColor(quote.status === 'final' ? colors.accentGreen : colors.warningAmber)
      .font('Helvetica-Bold')
      .text(quote.status.toUpperCase(), rightColX + 140, currentY);

    currentY += 20;
    doc
      .fontSize(11)
      .fillColor(colors.mediumText)
      .font('Helvetica')
      .text('Version:', rightColX, currentY);
    doc
      .fontSize(12)
      .fillColor(colors.darkText)
      .font('Helvetica-Bold')
      .text(quote.version.toString(), rightColX + 140, currentY);

    currentY += 45; // More space

    // Executive Summary - Larger font
    doc
      .fontSize(16)
      .font('Helvetica-Bold')
      .fillColor(colors.darkText)
      .text('EXECUTIVE SUMMARY', margin, currentY);

    currentY += 20;
    drawDivider(currentY);
    currentY += 15;

    const summaryText = `This comprehensive project estimation report outlines the scope, timeline, and commercials for developing ${quote.inputs.buildTypes.join(', ')}. We have analyzed your requirements across ${quote.inputs.features.length} features and prepared three delivery options tailored to different priorities: cost optimization, balanced approach, and fast-track delivery.`;

    doc
      .fontSize(11)
      .font('Helvetica')
      .fillColor(colors.mediumText)
      .text(summaryText, margin, currentY, { width: contentWidth, align: 'justify', lineGap: 4 }); // More line gap

    addFooter(1, 5);

    // ============ PAGE 2: PROJECT SCOPE & TECH STACK ============
    doc.addPage();
    currentY = margin;

    doc
      .fontSize(24)
      .font('Helvetica-Bold')
      .fillColor(colors.primary)
      .text('PROJECT SCOPE', margin, currentY);

    currentY += 35; // More space
    drawDivider(currentY, colors.primary, 2); // Thicker
    currentY += 25;

    // Project Goals
    doc
      .fontSize(14)
      .font('Helvetica-Bold')
      .fillColor(colors.darkText)
      .text('Project Goals & Objectives', margin, currentY);

    currentY += 20;
    doc
      .fontSize(11)
      .font('Helvetica')
      .fillColor(colors.mediumText)
      .text(quote.inputs.goals, margin, currentY, {
        width: contentWidth,
        align: 'justify',
        lineGap: 3,
      });

    currentY = doc.y + 25; // More space

    // Deliverables - Larger boxes
    doc
      .fontSize(14)
      .font('Helvetica-Bold')
      .fillColor(colors.darkText)
      .text('Deliverables', margin, currentY);

    currentY += 20;

    const boxWidth = (contentWidth - 16) / 2; // More space
    const boxHeight = 110;

    // Build Types Box
    drawSectionBox(margin, currentY, boxWidth, boxHeight, colors.sectionBg, colors.primary);
    doc
      .fontSize(13)
      .font('Helvetica-Bold')
      .fillColor(colors.primary)
      .text('Build Types', margin + 15, currentY + 12);

    let btY = currentY + 35; // Adjusted
    quote.inputs.buildTypes.forEach((type: string) => {
      doc
        .fontSize(11)
        .font('Helvetica')
        .fillColor(colors.darkText)
        .text(`• ${type}`, margin + 15, btY);
      btY += 16; // More spacing
    });

    // Artifacts Box
    drawSectionBox(
      margin + boxWidth + 16,
      currentY,
      boxWidth,
      boxHeight,
      colors.sectionBg,
      colors.accentBlue
    );
    doc
      .fontSize(13)
      .font('Helvetica-Bold')
      .fillColor(colors.accentBlue)
      .text('Artifacts', margin + boxWidth + 23, currentY + 12);

    let artY = currentY + 35;
    quote.inputs.artifacts.slice(0, 4).forEach((artifact: string) => {
      doc
        .fontSize(11)
        .font('Helvetica')
        .fillColor(colors.darkText)
        .text(`• ${artifact}`, margin + boxWidth + 23, artY);
      artY += 16;
    });

    currentY += boxHeight + 25; // More space

    // Feature Breakdown
    doc
      .fontSize(14)
      .font('Helvetica-Bold')
      .fillColor(colors.darkText)
      .text('Feature Breakdown', margin, currentY);

    currentY += 20;
    drawDivider(currentY);
    currentY += 15;

    const featureGroups = quote.inputs.features.reduce((acc: any, f: any) => {
      if (!acc[f.depth]) acc[f.depth] = [];
      acc[f.depth].push(capitalizeFirstWord(f.key));
      return acc;
    }, {});

    const depthColors: any = {
      basic: colors.accentGreen,
      standard: colors.accentBlue,
      advanced: colors.accentPurple,
    };
    let featuresY = currentY;

    Object.entries(featureGroups).forEach(([depth, features]: [string, any], idx: number) => {
      if (idx > 0) featuresY += 10;

      doc
        .fontSize(12)
        .font('Helvetica-Bold')
        .fillColor(depthColors[depth] || colors.primary)
        .text(`${depth.toUpperCase()} FEATURES`, margin, featuresY);

      featuresY += 15; // More space

      (features as string[]).forEach((feature: string) => {
        doc
          .fontSize(11)
          .font('Helvetica')
          .fillColor(colors.darkText)
          .text(`• ${feature}`, margin + 10, featuresY);
        featuresY += 15;
      });

      // if ((features as string[]).length > 3) {
      //   doc
      //     .fontSize(10)
      //     .font('Helvetica-Oblique')
      //     .fillColor(colors.lightText)
      //     .text(`+ ${(features as string[]).length - 3} more`, margin + 10, featuresY);
      //   featuresY += 13;
      // }
    });

    currentY = featuresY + 15;

    // Technical Specifications - Larger
    doc
      .fontSize(14)
      .font('Helvetica-Bold')
      .fillColor(colors.darkText)
      .text('Technical Specifications', margin, currentY);

    currentY += 18;
    drawDivider(currentY);
    currentY += 15;

    const techSpecs = [
      { label: 'Scale Band', value: quote.inputs.scaleBand },
      { label: 'Accessibility', value: quote.inputs.a11y ? 'Required' : 'Standard' },
      { label: 'Multi-language', value: quote.inputs.i18n ? 'Yes' : 'No' },
      { label: 'Performance', value: quote.inputs.perf ? 'Optimized' : 'Standard' },
      { label: 'Compliance', value: quote.inputs.compliance.toUpperCase() },
      {
        label: 'AI Integration',
        value: quote.inputs.includesAI ? `${quote.inputs.aiNovelty || 'standard'}` : 'No',
      },
    ];

    techSpecs.forEach((spec, idx) => {
      const xPos = idx % 2 === 0 ? margin : margin + contentWidth / 2 + 10;
      const yPos = currentY + Math.floor(idx / 2) * 26; // More spacing

      doc.fontSize(11).font('Helvetica').fillColor(colors.mediumText).text(spec.label, xPos, yPos);

      doc
        .fontSize(12)
        .font('Helvetica-Bold')
        .fillColor(colors.primary)
        .text(spec.value, xPos + 130, yPos); // More indent
    });

    currentY += Math.ceil(techSpecs.length / 2) * 26 + 20;

    // Technology Stack - Larger box
    doc
      .fontSize(14)
      .font('Helvetica-Bold')
      .fillColor(colors.darkText)
      .text('Technology Stack', margin, currentY);

    currentY += 18;
    drawSectionBox(margin, currentY, contentWidth, 65, colors.sectionBg, colors.primary); // Taller

    const stackItems = [
      { label: 'Frontend', value: quote.inputs.techPrefs.frontend },
      { label: 'Backend', value: quote.inputs.techPrefs.backend },
      { label: 'Database', value: quote.inputs.techPrefs.db },
      { label: 'Cloud', value: quote.inputs.techPrefs.cloud },
    ];

    stackItems.forEach((item, idx) => {
      const xPos = idx % 2 === 0 ? margin + 15 : margin + contentWidth / 2 + 15;
      const yPos = currentY + 15 + Math.floor(idx / 2) * 24; // More space

      doc.fontSize(11).font('Helvetica').fillColor(colors.mediumText).text(item.label, xPos, yPos);

      doc
        .fontSize(12)
        .font('Helvetica-Bold')
        .fillColor(colors.primary)
        .text(item.value, xPos + 90, yPos); // More indent
    });

    addFooter(2, 5);

    // ============ PAGE 3: PRICING OPTIONS ============
    doc.addPage();
    currentY = margin;

    doc
      .fontSize(24)
      .font('Helvetica-Bold')
      .fillColor(colors.primary)
      .text('PRICING & OPTIONS', margin, currentY);

    currentY += 32; // More space
    drawDivider(currentY, colors.primary, 2);
    currentY += 20;

    doc
      .fontSize(11)
      .font('Helvetica')
      .fillColor(colors.mediumText)
      .text(
        'Three tailored options designed to match your priorities. Each includes comprehensive development, testing, deployment, and post-launch support.',
        margin,
        currentY,
        { width: contentWidth, lineGap: 3 }
      );

    currentY += 35; // More space

    // Option Cards - Larger, better spaced, removed emojis to prevent garbling
    const optionConfigs = [
      { key: 'A', color: colors.accentGreen, label: 'COST OPTIMIZED' }, // Removed 💰
      { key: 'B', color: colors.accentBlue, label: 'BALANCED' }, // Removed ⚖️
      { key: 'C', color: colors.accentPurple, label: 'FAST TRACK' }, // Removed ⚡
    ];

    optionConfigs.forEach((optConfig, idx) => {
      const opt = (quote.options as any)[optConfig.key];
      const cardY = currentY + idx * 120;

      // Card border - Softer, explicit lineWidth
      doc
        .strokeColor(optConfig.color)
        .lineWidth(1)
        .roundedRect(margin, cardY, contentWidth, 110, 0) // Larger height, bigger radius
        .stroke();

      // Top colored bar - Taller
      doc.rect(margin, cardY, contentWidth, 30).fill(optConfig.color);
      doc
        .fontSize(12)
        .font('Helvetica-Bold')
        .fillColor(colors.white)
        .text(optConfig.label, margin + 15, cardY + 10, { width: contentWidth - 30 });

      // Recommended badge - Larger
      if (opt.recommended) {
        doc.roundedRect(pageWidth - margin - 112, cardY + 6, 95, 18, 9).fill(colors.white);
        doc
          .fontSize(10)
          .font('Helvetica-Bold')
          .fillColor(optConfig.color)
          .text('RECOMMENDED', pageWidth - margin - 105, cardY + 11);
      }

      // Content - Larger fonts, better spacing to prevent garbling/overlap
      const contentY = cardY + 40;

      // Timeline row
      doc
        .fontSize(11)
        .font('Helvetica')
        .fillColor(colors.mediumText)
        .text('Timeline:', margin + 15, contentY);
      doc
        .fontSize(12)
        .font('Helvetica-Bold')
        .fillColor(colors.darkText)
        .text(`${opt.weeks} weeks`, margin + 85, contentY);

      // Project Cost row - Same line, more space
      doc
        .fontSize(11)
        .font('Helvetica')
        .fillColor(colors.mediumText)
        .text('Project Cost:', margin + 200, contentY); // Adjusted from 220 for more space

      function formatIndianAmount(amount: number): string {
        if (amount >= 100000) {
          // 1 Lakh = 100000
          return `${(amount / 100000).toFixed(1)}L`;
        }
        if (amount >= 1000) {
          return `${(amount / 1000).toFixed(0)}K`;
        }
        return amount.toString();
      }

      const minFormatted = formatIndianAmount(opt.costMin);
      const maxFormatted = formatIndianAmount(opt.costMax);

      drawRupeesText(`₹${minFormatted} - ₹${maxFormatted}`, margin + 290, contentY - 4.5, {
        fontSize: 12,
        fillColor: colors.darkText,
      });

      // Cloud Infra row - Next line
      doc
        .fontSize(11)
        .font('Helvetica')
        .fillColor(colors.mediumText)
        .text('Cloud Infra (monthly):', margin + 15, contentY + 25);

      drawRupeesText(`₹${opt.cloudMonthly.toLocaleString()}`, margin + 125, contentY + 23, {
        fontSize: 11,
        fillColor: colors.darkText,
      });

      // Team text - Below, with width for wrapping, smaller font if needed
      const teamText = opt.team.map((t: any) => `${t.count}× ${t.role}`).join(' • ');
      doc
        .fontSize(11)
        .font('Helvetica')
        .fillColor(colors.lightText)
        .text(teamText, margin + 15, contentY + 50, { width: contentWidth - 30, lineGap: 2 });
    });

    addFooter(3, 5);

    // ============ PAGE 4: TERMS & CONDITIONS ============
    doc.addPage();
    currentY = margin;

    doc
      .fontSize(24)
      .font('Helvetica-Bold')
      .fillColor(colors.primary)
      .text('TERMS & CONDITIONS', margin, currentY);

    currentY += 32;
    drawDivider(currentY, colors.primary, 2);
    currentY += 20;

    // Assumptions - Larger
    doc
      .fontSize(13)
      .font('Helvetica-Bold')
      .fillColor(colors.darkText)
      .text('Assumptions', margin, currentY);

    currentY += 15;
    drawDivider(currentY);
    currentY += 12;

    quote.assumptions.forEach((assumption: string) => {
      doc
        .fontSize(11)
        .font('Helvetica')
        .fillColor(colors.mediumText)
        .text(`• ${assumption}`, margin + 10, currentY, { width: contentWidth - 20, lineGap: 2 });
      currentY = doc.y + 8;
    });

    currentY += 12;

    // Exclusions
    doc
      .fontSize(13)
      .font('Helvetica-Bold')
      .fillColor(colors.darkText)
      .text('Exclusions', margin, currentY);

    currentY += 15;
    drawDivider(currentY);
    currentY += 12;

    quote.exclusions.forEach((exclusion: string) => {
      doc
        .fontSize(11)
        .font('Helvetica')
        .fillColor(colors.mediumText)
        .text(`• ${exclusion}`, margin + 10, currentY, { width: contentWidth - 20, lineGap: 2 });
      currentY = doc.y + 8;
    });

    currentY += 12;

    // IP & Code Ownership
    doc
      .fontSize(13)
      .font('Helvetica-Bold')
      .fillColor(colors.darkText)
      .text('IP & Code Ownership', margin, currentY);

    currentY += 15;
    drawDivider(currentY);
    currentY += 12;

    const ipText =
      'Upon full payment, all source code, documentation, and intellectual property rights developed for this project will be transferred to the client. Trakshym retains rights to pre-existing frameworks, libraries, and reusable components.';

    doc
      .fontSize(11)
      .font('Helvetica')
      .fillColor(colors.mediumText)
      .text(ipText, margin, currentY, { width: contentWidth, align: 'justify', lineGap: 3 });

    currentY = doc.y + 18;

    // Payment Milestones - Larger box
    doc
      .fontSize(13)
      .font('Helvetica-Bold')
      .fillColor(colors.darkText)
      .text('Payment Terms (Milestone-based)', margin, currentY);

    currentY += 15;
    drawDivider(currentY);
    currentY += 12;

    drawSectionBox(margin, currentY, contentWidth, 75, colors.sectionBg, colors.accentBlue); // Taller

    const milestones = [
      { phase: 'Kickoff', pct: '30%', desc: 'Upon agreement' },
      { phase: 'Development', pct: '40%', desc: 'After UAT approval' },
      { phase: 'Completion', pct: '30%', desc: 'Final delivery' },
    ];

    milestones.forEach((m, idx) => {
      const xPos = margin + idx * (contentWidth / 3) + 15;
      const yPos = currentY + 18;

      doc.fontSize(12).font('Helvetica-Bold').fillColor(colors.accentBlue).text(m.pct, xPos, yPos);

      doc
        .fontSize(11)
        .font('Helvetica')
        .fillColor(colors.darkText)
        .text(m.phase, xPos, yPos + 18);

      doc
        .fontSize(10)
        .font('Helvetica-Oblique')
        .fillColor(colors.lightText)
        .text(m.desc, xPos, yPos + 34);
    });

    currentY += 90; // Adjusted

    // Support SLA - Larger
    doc
      .fontSize(13)
      .font('Helvetica-Bold')
      .fillColor(colors.darkText)
      .text('Post-Launch Support', margin, currentY);

    currentY += 15;
    drawDivider(currentY);
    currentY += 12;

    const supportText = `${quote.inputs.supportMonths} months of complimentary support. Critical issues: 4-hour response. Standard issues: 24-hour response (business days). Covers bug fixes, minor adjustments, and technical assistance.`;

    doc
      .fontSize(11)
      .font('Helvetica')
      .fillColor(colors.mediumText)
      .text(supportText, margin, currentY, { width: contentWidth, align: 'justify', lineGap: 3 });

    addFooter(4, 5);

    // ============ PAGE 5: CTA & QR CODE ============
    doc.addPage();
    currentY = margin + 50; // More top space

    // CTA Heading - Larger
    doc
      .fontSize(32)
      .font('Helvetica-Bold')
      .fillColor(colors.primary)
      .text("LET'S BUILD", margin, currentY, { width: contentWidth, align: 'center' });

    currentY += 42;
    doc
      .fontSize(32)
      .font('Helvetica-Bold')
      .fillColor(colors.primary)
      .text('THIS TOGETHER!', margin, currentY, { width: contentWidth, align: 'center' });

    currentY += 80; // More space

    // Main CTA box - Larger, rounder
    drawSectionBox(
      margin + 40,
      currentY,
      contentWidth - 80,
      135, // Taller
      colors.sectionBg,
      colors.primary,
      15 // Rounder
    );

    doc
      .fontSize(12)
      .font('Helvetica')
      .fillColor(colors.darkText)
      .text(
        "Thank you for considering Trakshym! We're excited to bring your vision to life.",
        margin + 55,
        currentY + 25,
        { width: contentWidth - 110, align: 'center', lineGap: 4 }
      );

    doc
      .fontSize(11)
      .font('Helvetica')
      .fillColor(colors.mediumText)
      .text('To discuss this quote or schedule a consultation:', margin + 55, currentY + 65, {
        width: contentWidth - 110,
        align: 'center',
        lineGap: 3,
      });

    doc
      .fontSize(14)
      .font('NotoSans')
      .fillColor(colors.primary)
      .text('contact@trakshym.com', margin + 55, currentY + 95, {
        width: contentWidth - 110,
        align: 'center',
      });

    currentY += 190; // Adjusted

    // QR Code & Contact Info Section - Larger QR
    const qrSize = 140;
    const qrX = margin + contentWidth / 2 - qrSize / 2;

    try {
      // Make QR rounded too
      doc.save();
      doc.roundedRect(qrX - 2, currentY - 2, qrSize + 4, qrSize + 4, 10).clip();
      doc.image(qrBuffer, qrX, currentY, { width: qrSize, height: qrSize });
      doc.restore();
    } catch (err) {
      // Fallback: draw QR code placeholder rect - rounded
      doc
        .strokeColor(colors.primary)
        .lineWidth(1)
        .roundedRect(qrX, currentY, qrSize, qrSize, 10)
        .stroke();
    }

    doc
      .fontSize(11)
      .font('Helvetica')
      .fillColor(colors.lightText)
      .text('Scan to schedule a call', margin, currentY + qrSize + 15, {
        width: contentWidth,
        align: 'center',
      });

    currentY += qrSize + 40;

    // Validity & Tax Info - Larger
    doc
      .fontSize(11)
      .font('Helvetica-Oblique')
      .fillColor(colors.mediumText)
      .text('This quote is valid for 30 days from the date of generation.', margin, currentY, {
        width: contentWidth,
        align: 'center',
        lineGap: 3,
      });

    doc
      .fontSize(11)
      .font('Helvetica-Oblique')
      .fillColor(colors.mediumText)
      .text('All prices in INR and exclusive of applicable taxes.', margin, currentY + 15, {
        width: contentWidth,
        align: 'center',
      });

    addFooter(5, 5);

    // FINALIZE
    doc.end();

    // Return the buffer when ready
    return await new Promise((resolve) => {
      doc.on('end', () => {
        resolve(Buffer.concat(chunks));
      });
    });
  } catch (err) {
    console.error('PDF generation error:', err);
    return null;
  }
};
